export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  ledgers: "/ledgers",
  ledgersJoin: "/ledgers/join",
  categories: "/more/categories",
  people: "/more/people",
  autoAccounting: "/more/auto",
  quickTemplates: "/more/quick",
  recordSettings: "/more/settings",
  systemSettings: "/more/system",
  feishu: "/more/feishu",
  notifications: "/more/notifications",
  /** 推送通知点进来的落地页：展示提醒内容，并承接飞书卡片上的那组动作。 */
  notification: (notificationId: string) => `/n/${notificationId}`,
  insurances: "/more/insurances",
  items: "/more/items",
  subscriptions: "/more/subscriptions",
  importExport: "/more/import-export",
  admin: "/more/admin",
  users: "/more/users",
  backup: "/more/backup",
  bills: "/bills",
  billNew: "/bills/new",
  billsPending: "/bills/pending",
  billPending: (pendingId: string) => `/bills/pending/${pendingId}`,
  billPendingEdit: (pendingId: string) => `/bills/pending/${pendingId}/edit`,
  bill: (transactionId: string) => `/bills/${transactionId}`,
  billEdit: (transactionId: string) => `/bills/${transactionId}/edit`,
  accounts: "/accounts",
  account: (accountId: string) => `/accounts/${accountId}`,
  subAccount: (accountId: string, subAccountId: string) => `/accounts/${accountId}/${subAccountId}`,
  stats: "/stats",
  budget: "/budget",
  more: "/more",
  ai: "/ai",
} as const;
