export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  ledgers: "/ledgers",
  ledgersJoin: "/ledgers/join",
  categories: "/more/categories",
  people: "/more/people",
  autoAccounting: "/more/auto",
  quickTemplates: "/more/quick",
  recordSettings: "/more/settings",
  insurances: "/more/insurances",
  items: "/more/items",
  importExport: "/more/import-export",
  bills: "/bills",
  billNew: "/bills/new",
  bill: (transactionId: string) => `/bills/${transactionId}`,
  billEdit: (transactionId: string) => `/bills/${transactionId}/edit`,
  accounts: "/accounts",
  account: (accountId: string) => `/accounts/${accountId}`,
  subAccount: (accountId: string, subAccountId: string) => `/accounts/${accountId}/${subAccountId}`,
  stats: "/stats",
  budget: "/budget",
  more: "/more",
} as const;
